## Numpy Array operations

In [13]:
import numpy as np

In [14]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing :",arr[2:7])
print("With step :",arr[1:8:2])
print("Negative Indexing : ",arr[:-3])


Basic Slicing : [3 4 5 6 7]
With step : [2 4 6 8]
Negative Indexing :  [1 2 3 4 5 6]


In [3]:
arr_2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Specific element is : ", arr_2d[1,2])
print("Entire row : ",arr_2d[1])
print("Entire column :",arr_2d[:,0])

Specific element is :  6
Entire row :  [4 5 6]
Entire column : [1 4 7]


## Sorting

In [ ]:
unsorted = np.array([5,3,6,8,9,1,4,8])
print("Sorted Array : ",np.sort(unsorted))
arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column :",np.sort(arr_2d_unsorted,axis=0))

Sorted Array :  [1 3 4 5 6 8 8 9]
Sorted 2D array by column : [[1 1]
 [2 2]
 [3 3]]


## Filter

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
even_number = numbers[numbers % 2 == 0]
print("Eve numbers : ",even_number)


Eve numbers :  [2 4 6 8]


## Filter with Mask

In [6]:
mask = numbers > 5
print("Numbers greater than 5 : ",numbers[mask])


Numbers greater than 5 :  [6 7 8 9]


## Fancy Indexing VS np.where()

In [7]:
indices = [0,2,4]
print(numbers[indices])

where_res = np.where(numbers > 5)
print(where_res)
print("NP where : ",numbers[where_res])


[1 3 5]
(array([5, 6, 7, 8]),)
NP where :  [6 7 8 9]


In [8]:
condition_array = np.where(numbers > 5,numbers * 2 ,numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18]


# Adding Or Removing data

In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


# Array Compatability

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("Compatibility shapes : ",a.shape == b.shape)

Compatibility shapes :  True


In [11]:
original = np.array([[1,2],[3,4]])
new_row = np.array([5,6])
with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)
new_column = np.array([[7],[8]])
with_new_column = np.hstack((original ,new_column))
print("With new column : ",with_new_column)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column :  [[1 2 7]
 [3 4 8]]


In [12]:
arr= np.array([1,2,3,4,5,6])
deleted = np.delete(arr,2)
print("Array after deletion :",deleted)

Array after deletion : [1 2 4 5 6]
